/**
 * PDF Export — renders a full invoice into a styled HTML page and triggers print-to-PDF.
 * Supports business branding (logo, stamp, signature) and layout_json template rendering.
 */

interface SimpleInvoiceData {
  client: string;
  items: { name: string; qty: number; price: number }[];
  gst: number;
  discount: number;
}

interface FullInvoiceData {
  invoice_number: string;
  issue_date: string;
  due_date?: string | null;
  status: string;
  subtotal: number;
  discount: number;
  gst_rate: number;
  gst_amount: number;
  total: number;
  currency: string;
  notes?: string | null;
  client_name?: string;
  client_email?: string;
  client_address?: string;
  client_gst?: string;
  items: { name: string; description?: string; quantity: number; unit_price: number; amount: number }[];
  // Business branding
  business_name?: string;
  business_email?: string;
  business_address?: string;
  business_gst?: string;
  logo_url?: string;
  stamp_url?: string;
  signature_url?: string;
  bank_account_name?: string;
  bank_account_number?: string;
  bank_ifsc?: string;
  bank_name?: string;
  bank_branch?: string;
  bank_upi_id?: string;
  layout_json?: any;
}

const fmt = (n: number, currency = "INR") => {
  if (currency === "USD") return `$${n.toLocaleString("en-US", { minimumFractionDigits: 2 })}`;
  return `₹${n.toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
};

const baseStyles = `
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  @page { size: A4; margin: 0; }
  body { font-family:'Inter',system-ui,sans-serif; color:#1a1a2e; background:#fff; padding:48px; margin:0; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:40px; }
  .brand { font-size:22px; font-weight:700; color:#1e3a5f; }
  .brand-logo { max-height:48px; max-width:180px; object-fit:contain; }
  .badge { background:#f0f4f8; color:#1e3a5f; padding:6px 14px; border-radius:6px; font-size:12px; font-weight:600; }
  .status-paid { background:#e6f9ee; color:#15803d; }
  .status-unpaid { background:#fef3cd; color:#92400e; }
  .status-overdue { background:#fee2e2; color:#dc2626; }
  .meta { display:grid; grid-template-columns:1fr 1fr; gap:32px; margin-bottom:36px; }
  .meta-label { font-size:10px; text-transform:uppercase; letter-spacing:0.08em; color:#8899a6; margin-bottom:4px; }
  .meta-value { font-size:14px; font-weight:500; }
  .meta-sub { font-size:12px; color:#666; margin-top:2px; }
  table { width:100%; border-collapse:collapse; margin-bottom:28px; }
  thead th { text-align:left; padding:10px 12px; font-size:10px; text-transform:uppercase; letter-spacing:0.06em; color:#8899a6; border-bottom:2px solid #e8edf2; }
  thead th:nth-child(n+3) { text-align:right; }
  td { padding:10px 12px; border-bottom:1px solid #eee; font-size:13px; }
  td:nth-child(n+3) { text-align:right; font-variant-numeric:tabular-nums; }
  td:first-child { color:#555; }
  .totals { margin-left:auto; width:280px; }
  .total-row { display:flex; justify-content:space-between; padding:6px 0; font-size:14px; }
  .total-row.grand { border-top:2px solid #1e3a5f; padding-top:10px; margin-top:6px; font-weight:700; font-size:16px; }
  .notes { margin-top:32px; padding:16px; background:#f8f9fa; border-radius:8px; font-size:12px; color:#555; }
  .notes-label { font-weight:600; margin-bottom:4px; font-size:11px; text-transform:uppercase; letter-spacing:0.05em; color:#888; }
  .footer { margin-top:48px; padding-top:20px; border-top:1px solid #eee; display:flex; justify-content:space-between; align-items:flex-end; }
  .footer-text { font-size:11px; color:#aaa; }
  .stamp-img { max-height:60px; max-width:120px; object-fit:contain; opacity:0.8; }
  .signature-block { text-align:right; }
  .signature-img { max-height:50px; max-width:160px; object-fit:contain; }
  .signature-label { font-size:10px; color:#888; margin-top:4px; border-top:1px solid #ccc; padding-top:4px; }
  @media print { body { padding:32px; } }
`;

const brandSection = (data: FullInvoiceData) => {
  if (data.logo_url) {
    return `<img src="${data.logo_url}" class="brand-logo" alt="Logo" />`;
  }
  return `<div class="brand">${data.business_name || "InvoiceFlow"}</div>`;
};

const footerSection = (data: FullInvoiceData) => {
  const parts: string[] = [];
  parts.push(
    `<div class="footer-text">Generated by ${data.business_name || "InvoiceFlow"} · ${new Date().toLocaleDateString("en-IN")}</div>`,
  );

  const rightParts: string[] = [];
  if (data.stamp_url) {
    rightParts.push(`<img src="${data.stamp_url}" class="stamp-img" alt="Stamp" />`);
  }
  if (data.signature_url) {
    rightParts.push(
      `<div class="signature-block"><img src="${data.signature_url}" class="signature-img" alt="Signature" /><div class="signature-label">Authorized Signatory</div></div>`,
    );
  }

  if (rightParts.length > 0) {
    parts.push(`<div style="display:flex;gap:24px;align-items:flex-end;">${rightParts.join("")}</div>`);
  }

  return `<div class="footer">${parts.join("")}</div>`;
};

const bankDetailsSection = (data: FullInvoiceData) => {
  const accName = data.bank_account_name;
  const accNum = data.bank_account_number;
  const ifsc = data.bank_ifsc;
  const bName = data.bank_name;
  const branch = data.bank_branch;
  const upi = data.bank_upi_id;
  if (!accName && !accNum && !ifsc && !bName && !upi) return "";
  return `
    <div style="margin-top:28px;padding:16px;background:#f8f9fa;border-radius:8px;">
      <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:8px;font-weight:600;">Bank Details</div>
      ${accName ? `<div style="font-size:13px;font-weight:500;margin-bottom:2px;">A/C Name: ${accName}</div>` : ""}
      ${accNum ? `<div style="font-size:11px;font-family:monospace;margin-bottom:2px;">A/C No: ${accNum}</div>` : ""}
      ${ifsc ? `<div style="font-size:12px;color:#666;margin-bottom:2px;">IFSC: ${ifsc}</div>` : ""}
      ${bName ? `<div style="font-size:12px;color:#666;margin-bottom:2px;">${bName}${branch ? ` — ${branch}` : ""}</div>` : ""}
      ${upi ? `<div style="font-size:12px;color:#666;">UPI: ${upi}</div>` : ""}
    </div>`;
};

const fromSection = (data: FullInvoiceData) => {
  if (!data.business_name && !data.business_email && !data.business_address) return "";
  return `
    <div>
      <div class="meta-label">From</div>
      <div class="meta-value">${data.business_name || ""}</div>
      ${data.business_email ? `<div class="meta-sub">${data.business_email}</div>` : ""}
      ${data.business_address ? `<div class="meta-sub">${data.business_address}</div>` : ""}
      ${data.business_gst ? `<div class="meta-sub" style="font-family:monospace;font-size:11px;margin-top:4px;">GST: ${data.business_gst}</div>` : ""}
    </div>
  `;
};

/** Export a simple invoice (from AI generator) */
export function exportInvoicePDF(data: SimpleInvoiceData, title = "Invoice") {
  const subtotal = data.items.reduce((s, i) => s + i.qty * i.price, 0);
  const gstAmt = (subtotal * data.gst) / 100;
  const discAmt = (subtotal * data.discount) / 100;
  const total = subtotal + gstAmt - discAmt;

  const itemsRows = data.items
    .map(
      (item, i) => `
    <tr><td>${i + 1}</td><td>${item.name}</td><td>${item.qty}</td><td>${fmt(item.price)}</td><td style="font-weight:500;">${fmt(item.qty * item.price)}</td></tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html><html><head><title>${title}</title><style>${baseStyles}</style></head><body>
  <div class="header"><div class="brand">InvoiceFlow</div><div class="badge">INVOICE</div></div>
  <div class="meta">
    <div><div class="meta-label">Bill To</div><div class="meta-value">${data.client}</div></div>
    <div style="text-align:right;"><div class="meta-label">Date</div><div class="meta-value">${new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}</div></div>
  </div>
  <table><thead><tr><th>#</th><th>Item</th><th>Qty</th><th>Price</th><th>Amount</th></tr></thead><tbody>${itemsRows}</tbody></table>
  <div class="totals">
    <div class="total-row"><span>Subtotal</span><span>${fmt(subtotal)}</span></div>
    ${data.gst > 0 ? `<div class="total-row"><span>GST (${data.gst}%)</span><span>+${fmt(gstAmt)}</span></div>` : ""}
    ${data.discount > 0 ? `<div class="total-row"><span>Discount (${data.discount}%)</span><span style="color:#2e8b57;">-${fmt(discAmt)}</span></div>` : ""}
    <div class="total-row grand"><span>Total</span><span>${fmt(total)}</span></div>
  </div>
  <div class="footer"><div class="footer-text">Generated by InvoiceFlow · ${new Date().toLocaleDateString("en-IN")}</div></div>
  <script>window.onload = function() { window.print(); }</script>
</body></html>`;
  openPrintWindow(html);
}

/** Export a full database invoice with business branding */
export function exportFullInvoicePDF(data: FullInvoiceData) {
  // If layout_json exists, use template-based rendering for PDF
  if (data.layout_json) {
    const templateHTML = renderTemplateHTML(data);
    if (templateHTML) {
      const html = `<!DOCTYPE html><html><head><title>${data.invoice_number}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Merriweather:wght@400;700&family=JetBrains+Mono:wght@400;500;600&display=swap');
          @page { size: ${(() => { const lo = data.layout_json as any; const ps = lo?.pageSize; return ps === 'a4' ? '210mm 297mm' : ps === 'letter' ? '8.5in 11in' : lo?.canvasWidth ? `${lo.canvasWidth}px ${lo.canvasHeight || 900}px` : '640px 900px'; })()}; margin: 0; }
          * { margin:0; padding:0; box-sizing:border-box; }
          html, body { width:100%; height:100%; }
          body { font-family:'Inter',system-ui,sans-serif; background:#fff; }
        </style>
      </head><body>${templateHTML}<script>window.onload=function(){window.print();}</script></body></html>`;
      openPrintWindow(html);
      return;
    }
  }

  const itemsRows = data.items
    .map(
      (item, i) => `
    <tr><td>${i + 1}</td><td>${item.name}${item.description ? `<div style="font-size:11px;color:#888;margin-top:2px;">${item.description}</div>` : ""}</td><td>${item.quantity}</td><td>${fmt(item.unit_price, data.currency)}</td><td style="font-weight:500;">${fmt(item.amount, data.currency)}</td></tr>`,
    )
    .join("");

  const statusClass = `status-${data.status}`;

  const html = `<!DOCTYPE html><html><head><title>${data.invoice_number}</title><style>${baseStyles}</style></head><body>
  <div class="header">
    ${brandSection(data)}
    <div style="text-align:right;">
      <div class="badge ${statusClass}" style="margin-bottom:8px;text-transform:uppercase;">${data.status}</div>
      <div style="font-size:18px;font-weight:700;color:#1e3a5f;">${data.invoice_number}</div>
    </div>
  </div>

  <div class="meta">
    ${fromSection(data) || "<div></div>"}
    <div>
      <div class="meta-label">Bill To</div>
      <div class="meta-value">${data.client_name || "—"}</div>
      ${data.client_email ? `<div class="meta-sub">${data.client_email}</div>` : ""}
      ${data.client_address ? `<div class="meta-sub">${data.client_address}</div>` : ""}
      ${data.client_gst ? `<div class="meta-sub" style="font-family:monospace;font-size:11px;margin-top:4px;">GST: ${data.client_gst}</div>` : ""}
    </div>
  </div>

  <div class="meta">
    <div>
      <div class="meta-label">Issue Date</div>
      <div class="meta-value">${data.issue_date}</div>
    </div>
    ${data.due_date ? `<div><div class="meta-label">Due Date</div><div class="meta-value">${data.due_date}</div></div>` : "<div></div>"}
  </div>

  <table><thead><tr><th>#</th><th>Item</th><th>Qty</th><th>Price</th><th>Amount</th></tr></thead><tbody>${itemsRows}</tbody></table>

  <div class="totals">
    <div class="total-row"><span>Subtotal</span><span>${fmt(Number(data.subtotal), data.currency)}</span></div>
    ${Number(data.gst_rate) > 0 ? `<div class="total-row"><span>GST (${data.gst_rate}%)</span><span>+${fmt(Number(data.gst_amount), data.currency)}</span></div>` : ""}
    ${Number(data.discount) > 0 ? `<div class="total-row"><span>Discount</span><span style="color:#2e8b57;">-${fmt(Number(data.discount), data.currency)}</span></div>` : ""}
    <div class="total-row grand"><span>Total</span><span>${fmt(Number(data.total), data.currency)}</span></div>
  </div>

  ${data.notes ? `<div class="notes"><div class="notes-label">Notes</div>${data.notes}</div>` : ""}

  ${bankDetailsSection(data)}

  ${footerSection(data)}
  <script>window.onload = function() { window.print(); }</script>
</body></html>`;
  openPrintWindow(html);
}

/** Render a single builder element to HTML — uses exact pixel positions from canvas */
function renderBuilderElement(el: any, data: FullInvoiceData): string {
  const c = el.content || {};
  const fontFamily = c.fontFamily === 'serif' ? "'Merriweather','Georgia',serif"
    : c.fontFamily === 'mono' ? "'JetBrains Mono','Courier New',monospace"
    : "'Inter',system-ui,sans-serif";
  // Use exact pixel positions — these include alignment-guide snapped values
  const style = `position:absolute;left:${el.x}px;top:${el.y}px;width:${el.width}px;height:${el.height}px;overflow:hidden;`;

  switch (el.type) {
    case "text": {
      const fs = c.fontSize || 14;
      const fw = c.fontWeight || (c.bold ? 700 : 400);
      const color = c.color ? `color:${c.color};` : "";
      const textAlign = c.textAlign ? `text-align:${c.textAlign};` : "";
      const lineHeight = c.lineHeight ? `line-height:${c.lineHeight};` : "line-height:1.4;";
      const letterSpacing = typeof c.letterSpacing === 'number' ? `letter-spacing:${c.letterSpacing}px;` : "";
      const italic = c.italic ? "font-style:italic;" : "";
      const underline = c.underline ? "text-decoration:underline;" : "";
      const textTransform = c.textTransform && c.textTransform !== 'none' ? `text-transform:${c.textTransform};` : "";
      const bgColor = c.backgroundColor && c.backgroundColor !== 'transparent' ? `background-color:${c.backgroundColor};` : "";
      const text = c.text || "";
      const rendered = text
        .replace(/\{\{invoice_number\}\}/g, data.invoice_number || "")
        .replace(/\{\{issue_date\}\}/g, data.issue_date || "")
        .replace(/\{\{due_date\}\}/g, data.due_date || "")
        .replace(/\{\{status\}\}/g, data.status || "")
        .replace(/\{\{total\}\}/g, fmt(Number(data.total), data.currency))
        .replace(/\{\{business_name\}\}/g, data.business_name || "")
        .replace(/\{\{client_name\}\}/g, data.client_name || "");
      return `<div style="${style}font-family:${fontFamily};font-size:${fs}px;font-weight:${fw};${color}${textAlign}${lineHeight}${letterSpacing}${italic}${underline}${textTransform}${bgColor}display:flex;align-items:center;padding:0 12px;">${rendered}</div>`;
    }
    case "logo": {
      const url = data.logo_url || el.content?.url;
      if (url) {
        return `<div style="${style}"><img src="${url}" style="max-width:100%;max-height:100%;object-fit:contain;" alt="Logo" /></div>`;
      }
      return `<div style="${style}font-size:20px;font-weight:700;color:#1e3a5f;">${data.business_name || "InvoiceFlow"}</div>`;
    }
    case "client-details": {
      return `<div style="${style}">
        <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:4px;">Bill To</div>
        <div style="font-size:14px;font-weight:500;">${data.client_name || "—"}</div>
        ${data.client_email ? `<div style="font-size:12px;color:#666;margin-top:2px;">${data.client_email}</div>` : ""}
        ${data.client_address ? `<div style="font-size:12px;color:#666;margin-top:2px;">${data.client_address}</div>` : ""}
        ${data.client_gst ? `<div style="font-size:11px;font-family:monospace;color:#666;margin-top:4px;">GST: ${data.client_gst}</div>` : ""}
      </div>`;
    }
    case "items-table": {
      const thStyle = "text-align:left;padding:6px 8px;font-size:9px;text-transform:uppercase;letter-spacing:0.06em;color:#8899a6;border-bottom:2px solid #e8edf2;";
      const thStyleR = thStyle.replace("text-align:left", "text-align:right");
      const thStyleC = thStyle.replace("text-align:left", "text-align:center");
      const tdStyle = "padding:6px 8px;border-bottom:1px solid #eee;font-size:12px;";
      const tdStyleR = tdStyle + "text-align:right;";
      const tdStyleC = tdStyle + "text-align:center;";
      const gstLabels: Record<string, string> = { none: "—", cgst_sgst: "CGST+SGST", igst: "IGST", cgst_utgst: "CGST+UTGST" };
      const vis = c.visibleColumns || { slNo: true, description: true, hsnSac: true, qty: true, price: true, gstType: true, gstRate: true, gstAmt: true, total: true };
      const cols = c.columns || { slNo: "Sl.No", description: "Description", hsnSac: "HSN/SAC", qty: "Qty", price: "Price", gstType: "GST Type", gstRate: "GST%", gstAmt: "GST Amt", total: "Total" };
      const rows = data.items
        .map(
          (item: any, i) => {
            const gstType = item.gst_type || "none";
            const gstRate = item.gst_rate || 0;
            const base = item.amount || (item.quantity * item.unit_price);
            const gstAmt = gstType !== "none" && gstRate > 0 ? (base * gstRate) / 100 : 0;
            return `<tr>
          ${vis.slNo !== false ? `<td style="${tdStyleC}">${i + 1}</td>` : ""}
          ${vis.description !== false ? `<td style="${tdStyle}">${item.name}${item.description ? `<div style="font-size:10px;color:#888;">${item.description}</div>` : ""}</td>` : ""}
          ${vis.hsnSac !== false ? `<td style="${tdStyleC};font-size:10px;">${(item as any).hsn_sac || "—"}</td>` : ""}
          ${vis.qty !== false ? `<td style="${tdStyleR}">${item.quantity}</td>` : ""}
          ${vis.price !== false ? `<td style="${tdStyleR}">${fmt(item.unit_price, data.currency)}</td>` : ""}
          ${vis.gstType !== false ? `<td style="${tdStyleC};font-size:10px;">${gstLabels[gstType] || "—"}</td>` : ""}
          ${vis.gstRate !== false ? `<td style="${tdStyleR}">${gstRate > 0 ? gstRate + "%" : "—"}</td>` : ""}
          ${vis.gstAmt !== false ? `<td style="${tdStyleR}">${gstAmt > 0 ? fmt(gstAmt, data.currency) : "—"}</td>` : ""}
          ${vis.total !== false ? `<td style="${tdStyleR}font-weight:500;">${fmt(base + gstAmt, data.currency)}</td>` : ""}
        </tr>`;
          },
        )
        .join("");
      return `<div style="${style}overflow:auto;">
        <table style="width:100%;border-collapse:collapse;">
          <thead><tr>
            ${vis.slNo !== false ? `<th style="${thStyleC}">${cols.slNo || "Sl.No"}</th>` : ""}
            ${vis.description !== false ? `<th style="${thStyle}">${cols.description}</th>` : ""}
            ${vis.qty !== false ? `<th style="${thStyleR}">${cols.qty}</th>` : ""}
            ${vis.price !== false ? `<th style="${thStyleR}">${cols.price}</th>` : ""}
            ${vis.gstType !== false ? `<th style="${thStyleC}">${cols.gstType || "GST Type"}</th>` : ""}
            ${vis.gstRate !== false ? `<th style="${thStyleR}">${cols.gstRate || "GST%"}</th>` : ""}
            ${vis.gstAmt !== false ? `<th style="${thStyleR}">${cols.gstAmt || "GST Amt"}</th>` : ""}
            ${vis.total !== false ? `<th style="${thStyleR}">${cols.total}</th>` : ""}
          </tr></thead>
          <tbody>${rows}</tbody>
        </table>
      </div>`;
    }
    case "total-summary": {
      return `<div style="${style}">
        <div style="display:flex;justify-content:space-between;padding:4px 0;font-size:13px;"><span>Subtotal</span><span>${fmt(Number(data.subtotal), data.currency)}</span></div>
        ${Number(data.gst_rate) > 0 ? `<div style="display:flex;justify-content:space-between;padding:4px 0;font-size:13px;"><span>GST (${data.gst_rate}%)</span><span>+${fmt(Number(data.gst_amount), data.currency)}</span></div>` : ""}
        ${Number(data.discount) > 0 ? `<div style="display:flex;justify-content:space-between;padding:4px 0;font-size:13px;"><span>Discount</span><span style="color:#2e8b57;">-${fmt(Number(data.discount), data.currency)}</span></div>` : ""}
        <div style="display:flex;justify-content:space-between;padding:8px 0;font-size:15px;font-weight:700;border-top:2px solid #1e3a5f;margin-top:4px;"><span>Total</span><span>${fmt(Number(data.total), data.currency)}</span></div>
      </div>`;
    }
    case "signature": {
      const url = data.signature_url;
      return `<div style="${style}text-align:center;">
        ${url ? `<img src="${url}" style="max-height:40px;max-width:140px;object-fit:contain;" alt="Signature" />` : '<div style="height:40px;border-bottom:1px solid #ccc;"></div>'}
        <div style="font-size:10px;color:#888;margin-top:4px;">${el.content?.label || "Authorized Signatory"}</div>
      </div>`;
    }
    case "divider": {
      const divStyle = c.style || "solid";
      const divColor = c.color || "#ddd";
      const divThickness = c.thickness || 1;
      const divSpacing = c.spacing || 0;
      return `<div style="${style}display:flex;align-items:center;padding:0 16px;margin-top:${divSpacing}px;margin-bottom:${divSpacing}px;"><hr style="width:100%;border:none;border-top:${divThickness}px ${divStyle} ${divColor};" /></div>`;
    }
    case "stamp": {
      const url = data.stamp_url || el.content?.url;
      if (url) {
        return `<div style="${style}text-align:center;"><img src="${url}" style="max-width:100%;max-height:100%;object-fit:contain;opacity:0.85;" alt="Stamp" /></div>`;
      }
      return `<div style="${style}text-align:center;font-size:10px;color:#aaa;border:1px dashed #ddd;display:flex;align-items:center;justify-content:center;">Stamp</div>`;
    }
    case "business-details": {
      return `<div style="${style}">
        <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:4px;">From</div>
        <div style="font-size:14px;font-weight:500;">${data.business_name || el.content?.name || ""}</div>
        ${data.business_email || el.content?.email ? `<div style="font-size:12px;color:#666;margin-top:2px;">${data.business_email || el.content?.email}</div>` : ""}
        ${el.content?.phone || "" ? `<div style="font-size:12px;color:#666;margin-top:2px;">${el.content?.phone}</div>` : ""}
        ${data.business_address || el.content?.address ? `<div style="font-size:12px;color:#666;margin-top:2px;">${data.business_address || el.content?.address}</div>` : ""}
        ${data.business_gst || el.content?.gst ? `<div style="font-size:11px;font-family:monospace;color:#666;margin-top:4px;">GST: ${data.business_gst || el.content?.gst}</div>` : ""}
      </div>`;
    }
    case "note": {
      const fs = c.fontSize || 12;
      const fw = c.fontWeight || 400;
      const color = c.color || "#555";
      const textAlign = c.textAlign ? `text-align:${c.textAlign};` : "";
      const lineHeight = c.lineHeight ? `line-height:${c.lineHeight};` : "line-height:1.4;";
      const noteText = (c.text || data.notes || "").replace(/\{\{notes\}\}/g, data.notes || "");
      return `<div style="${style}">
        <div style="padding:10px;background:#f8f9fa;border-radius:6px;font-family:${fontFamily};${textAlign}${lineHeight}">
          <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#888;margin-bottom:4px;font-weight:600;">Note</div>
          <div style="font-size:${fs}px;font-weight:${fw};color:${color};">${noteText}</div>
        </div>
      </div>`;
    }
    case "invoice-number": {
      const label = el.content?.label || "Invoice #";
      const value = (el.content?.value || "{{invoice_number}}")
        .replace(/\{\{invoice_number\}\}/g, data.invoice_number || "");
      return `<div style="${style}">
        <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:4px;">${label}</div>
        <div style="font-size:15px;font-weight:600;font-family:'Courier New',monospace;">${value}</div>
      </div>`;
    }
    case "invoice-date": {
      const label = el.content?.label || "Date";
      const showIssue = el.content?.showIssue !== false;
      const showDue = el.content?.showDue !== false;
      let dateHtml = `<div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:6px;">${label}</div>`;
      if (showIssue) {
        dateHtml += `<div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:3px;"><span style="color:#8899a6;">Issue:</span><span style="font-weight:500;">${data.issue_date || "—"}</span></div>`;
      }
      if (showDue) {
        dateHtml += `<div style="display:flex;justify-content:space-between;font-size:12px;"><span style="color:#8899a6;">Due:</span><span style="font-weight:500;">${data.due_date || "—"}</span></div>`;
      }
      return `<div style="${style}">${dateHtml}</div>`;
    }
    case "bank-details": {
      const accName = data.bank_account_name || c.accountName || "";
      const accNum = data.bank_account_number || c.accountNumber || "";
      const ifsc = data.bank_ifsc || c.ifsc || "";
      const bName = data.bank_name || c.bankName || "";
      const branch = data.bank_branch || c.branch || "";
      const upi = data.bank_upi_id || c.upiId || "";
      const ff = `font-family:${fontFamily};`;
      const fs = c.fontSize ? `font-size:${c.fontSize}px;` : "";
      return `<div style="${style}${ff}${fs}">
        <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:4px;font-weight:600;">Bank Details</div>
        ${accName ? `<div style="font-size:13px;font-weight:500;margin-bottom:2px;">A/C Name: ${accName}</div>` : ""}
        ${accNum ? `<div style="font-size:11px;font-family:monospace;margin-bottom:2px;">A/C No: ${accNum}</div>` : ""}
        ${ifsc ? `<div style="font-size:12px;color:#666;margin-bottom:2px;">IFSC: ${ifsc}</div>` : ""}
        ${bName ? `<div style="font-size:12px;color:#666;margin-bottom:2px;">${bName}${branch ? ` — ${branch}` : ""}</div>` : ""}
        ${upi ? `<div style="font-size:12px;color:#666;">UPI: ${upi}</div>` : ""}
      </div>`;
    }
    default:
      return "";
  }
}

/** Render using layout_json template */
function renderTemplateHTML(data: FullInvoiceData): string {
  const layoutObj = data.layout_json as any;
  const elements = Array.isArray(layoutObj) ? layoutObj : layoutObj?.elements || [];
  if (!elements.length) return null as any;

  const canvasWidth = Number(layoutObj?.canvasWidth) || 640;
  const canvasHeight = Number(layoutObj?.canvasHeight) || (() => {
    let maxBottom = 600;
    elements.forEach((el: any) => {
      const bottom = (el.y || 0) + (el.height || 0);
      if (bottom > maxBottom) maxBottom = bottom;
    });
    return maxBottom;
  })();

  const rendered = elements.map((el: any) => renderBuilderElement(el, data)).join("");

  // Container matches canvas dimensions exactly — no padding, no margin adjustments
  return `
  <div style="font-family:'Inter',system-ui,sans-serif;color:#1a1a2e;position:relative;width:${canvasWidth}px;height:${canvasHeight}px;margin:0 auto;overflow:hidden;box-sizing:border-box;">
    ${rendered}
  </div>`;
}

/** Generate HTML string for invoice preview (no auto-print) */
export function generateInvoicePreviewHTML(data: FullInvoiceData): string {
  // If layout_json exists, use template-based rendering
  if (data.layout_json) {
    const templateHTML = renderTemplateHTML(data);
    if (templateHTML) return templateHTML;
  }

  // Fallback to default layout
  const itemsRows = data.items
    .map(
      (item, i) => `
    <tr>
      <td>${i + 1}</td>
      <td>${item.name}${item.description ? `<div style="font-size:11px;color:#888;margin-top:2px;">${item.description}</div>` : ""}</td>
      <td>${item.quantity}</td>
      <td>${fmt(item.unit_price, data.currency)}</td>
      <td style="font-weight:500;">${fmt(item.amount, data.currency)}</td>
    </tr>`,
    )
    .join("");

  const statusStyle =
    data.status === "paid"
      ? "background:#e6f9ee;color:#15803d;"
      : data.status === "overdue"
        ? "background:#fee2e2;color:#dc2626;"
        : "background:#fef3cd;color:#92400e;";

  const logoHtml = data.logo_url
    ? `<img src="${data.logo_url}" style="max-height:40px;max-width:160px;object-fit:contain;" alt="Logo" />`
    : `<div style="font-size:20px;font-weight:700;color:#1e3a5f;">${data.business_name || "InvoiceFlow"}</div>`;

  const fromHtml =
    data.business_name || data.business_email || data.business_address
      ? `<div>
        <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:4px;">From</div>
        <div style="font-size:14px;font-weight:500;">${data.business_name || ""}</div>
        ${data.business_email ? `<div style="font-size:12px;color:#666;margin-top:2px;">${data.business_email}</div>` : ""}
        ${data.business_address ? `<div style="font-size:12px;color:#666;margin-top:2px;">${data.business_address}</div>` : ""}
        ${data.business_gst ? `<div style="font-size:11px;font-family:monospace;color:#666;margin-top:4px;">GST: ${data.business_gst}</div>` : ""}
      </div>`
      : "";

  const footerHtml = `
    <div style="margin-top:40px;padding-top:16px;border-top:1px solid #eee;display:flex;justify-content:space-between;align-items:flex-end;">
      <div style="font-size:11px;color:#aaa;">Generated by ${data.business_name || "InvoiceFlow"}</div>
      <div style="display:flex;gap:20px;align-items:flex-end;">
        ${data.stamp_url ? `<img src="${data.stamp_url}" style="max-height:50px;max-width:100px;object-fit:contain;opacity:0.8;" alt="Stamp" />` : ""}
        ${data.signature_url ? `<div style="text-align:right;"><img src="${data.signature_url}" style="max-height:40px;max-width:140px;object-fit:contain;" alt="Signature" /><div style="font-size:10px;color:#888;margin-top:4px;border-top:1px solid #ccc;padding-top:4px;">Authorized Signatory</div></div>` : ""}
      </div>
    </div>`;

  return `
  <div style="font-family:'Inter',system-ui,sans-serif;color:#1a1a2e;padding:32px;max-width:640px;margin:0 auto;">
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px;">
      ${logoHtml}
      <div style="text-align:right;">
        <span style="display:inline-block;padding:4px 10px;border-radius:6px;font-size:11px;font-weight:600;text-transform:uppercase;${statusStyle}">${data.status}</span>
        <div style="font-size:16px;font-weight:700;color:#1e3a5f;margin-top:6px;">${data.invoice_number}</div>
      </div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:28px;">
      ${fromHtml || "<div></div>"}
      <div>
        <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:4px;">Bill To</div>
        <div style="font-size:14px;font-weight:500;">${data.client_name || "—"}</div>
        ${data.client_email ? `<div style="font-size:12px;color:#666;margin-top:2px;">${data.client_email}</div>` : ""}
        ${data.client_address ? `<div style="font-size:12px;color:#666;margin-top:2px;">${data.client_address}</div>` : ""}
      </div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px;">
      <div>
        <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:4px;">Issue Date</div>
        <div style="font-size:14px;font-weight:500;">${data.issue_date}</div>
      </div>
      ${data.due_date ? `<div><div style="font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8899a6;margin-bottom:4px;">Due Date</div><div style="font-size:14px;font-weight:500;">${data.due_date}</div></div>` : "<div></div>"}
    </div>
    <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
      <thead><tr>
        <th style="text-align:left;padding:8px 10px;font-size:10px;text-transform:uppercase;letter-spacing:0.06em;color:#8899a6;border-bottom:2px solid #e8edf2;">#</th>
        <th style="text-align:left;padding:8px 10px;font-size:10px;text-transform:uppercase;letter-spacing:0.06em;color:#8899a6;border-bottom:2px solid #e8edf2;">Item</th>
        <th style="text-align:right;padding:8px 10px;font-size:10px;text-transform:uppercase;letter-spacing:0.06em;color:#8899a6;border-bottom:2px solid #e8edf2;">Qty</th>
        <th style="text-align:right;padding:8px 10px;font-size:10px;text-transform:uppercase;letter-spacing:0.06em;color:#8899a6;border-bottom:2px solid #e8edf2;">Price</th>
        <th style="text-align:right;padding:8px 10px;font-size:10px;text-transform:uppercase;letter-spacing:0.06em;color:#8899a6;border-bottom:2px solid #e8edf2;">Amount</th>
      </tr></thead>
      <tbody>${itemsRows}</tbody>
    </table>
    <div style="margin-left:auto;width:240px;">
      <div style="display:flex;justify-content:space-between;padding:5px 0;font-size:13px;"><span>Subtotal</span><span>${fmt(Number(data.subtotal), data.currency)}</span></div>
      ${Number(data.gst_rate) > 0 ? `<div style="display:flex;justify-content:space-between;padding:5px 0;font-size:13px;"><span>GST (${data.gst_rate}%)</span><span>+${fmt(Number(data.gst_amount), data.currency)}</span></div>` : ""}
      ${Number(data.discount) > 0 ? `<div style="display:flex;justify-content:space-between;padding:5px 0;font-size:13px;"><span>Discount</span><span style="color:#2e8b57;">-${fmt(Number(data.discount), data.currency)}</span></div>` : ""}
      <div style="display:flex;justify-content:space-between;padding:8px 0;font-size:15px;font-weight:700;border-top:2px solid #1e3a5f;margin-top:4px;"><span>Total</span><span>${fmt(Number(data.total), data.currency)}</span></div>
    </div>
    ${data.notes ? `<div style="margin-top:24px;padding:12px;background:#f8f9fa;border-radius:8px;font-size:12px;color:#555;"><div style="font-weight:600;margin-bottom:4px;font-size:11px;text-transform:uppercase;color:#888;">Notes</div>${data.notes}</div>` : ""}
    ${bankDetailsSection(data)}
    ${footerHtml}
  </div>`;
}

function openPrintWindow(html: string) {
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
  }
}
