/**
 * PDF Export — uses the browser's print-to-PDF via a hidden iframe.
 * Renders the invoice HTML into a styled iframe and triggers window.print().
 */

interface InvoiceData {
  client: string;
  items: { name: string; qty: number; price: number }[];
  gst: number;
  discount: number;
}

const fmt = (n: number) => `₹${n.toLocaleString("en-IN")}`;

export function exportInvoicePDF(data: InvoiceData, title = "Invoice") {
  const subtotal = data.items.reduce((s, i) => s + i.qty * i.price, 0);
  const gstAmt = (subtotal * data.gst) / 100;
  const discAmt = (subtotal * data.discount) / 100;
  const total = subtotal + gstAmt - discAmt;

  const itemsRows = data.items
    .map(
      (item, i) => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #eee;color:#555;">${i + 1}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eee;">${item.name}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eee;text-align:right;font-variant-numeric:tabular-nums;">${item.qty}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eee;text-align:right;font-variant-numeric:tabular-nums;">${fmt(item.price)}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #eee;text-align:right;font-weight:500;font-variant-numeric:tabular-nums;">${fmt(item.qty * item.price)}</td>
    </tr>`
    )
    .join("");

  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:'Inter',system-ui,sans-serif; color:#1a1a2e; background:#fff; padding:48px; }
    .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:40px; }
    .brand { font-size:22px; font-weight:700; color:#1e3a5f; }
    .badge { background:#f0f4f8; color:#1e3a5f; padding:6px 14px; border-radius:6px; font-size:12px; font-weight:600; }
    .meta { display:grid; grid-template-columns:1fr 1fr; gap:32px; margin-bottom:36px; }
    .meta-label { font-size:10px; text-transform:uppercase; letter-spacing:0.08em; color:#8899a6; margin-bottom:4px; }
    .meta-value { font-size:14px; font-weight:500; }
    table { width:100%; border-collapse:collapse; margin-bottom:28px; }
    thead th { text-align:left; padding:10px 12px; font-size:10px; text-transform:uppercase; letter-spacing:0.06em; color:#8899a6; border-bottom:2px solid #e8edf2; }
    thead th:nth-child(n+3) { text-align:right; }
    .totals { margin-left:auto; width:280px; }
    .total-row { display:flex; justify-content:space-between; padding:6px 0; font-size:14px; }
    .total-row.grand { border-top:2px solid #1e3a5f; padding-top:10px; margin-top:6px; font-weight:700; font-size:16px; }
    .footer { margin-top:48px; padding-top:20px; border-top:1px solid #eee; font-size:11px; color:#aaa; text-align:center; }
    @media print { body { padding:32px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">InvoiceFlow</div>
    <div class="badge">INVOICE</div>
  </div>

  <div class="meta">
    <div>
      <div class="meta-label">Bill To</div>
      <div class="meta-value">${data.client}</div>
    </div>
    <div style="text-align:right;">
      <div class="meta-label">Date</div>
      <div class="meta-value">${new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Item</th>
        <th>Qty</th>
        <th>Price</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      ${itemsRows}
    </tbody>
  </table>

  <div class="totals">
    <div class="total-row"><span>Subtotal</span><span>${fmt(subtotal)}</span></div>
    ${data.gst > 0 ? `<div class="total-row"><span>GST (${data.gst}%)</span><span>+${fmt(gstAmt)}</span></div>` : ""}
    ${data.discount > 0 ? `<div class="total-row"><span>Discount (${data.discount}%)</span><span style="color:#2e8b57;">-${fmt(discAmt)}</span></div>` : ""}
    <div class="total-row grand"><span>Total</span><span>${fmt(total)}</span></div>
  </div>

  <div class="footer">Generated by InvoiceFlow · ${new Date().toLocaleDateString("en-IN")}</div>

  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
  }
}
